In [61]:
import numpy as np
from scipy.stats import unitary_group
from numpy.linalg import inv
from numpy.linalg import eig

In [62]:
U = unitary_group.rvs(4)
M1 = np.reshape(U[0], (2,2))/2**0.5
M2 = np.reshape(U[1], (2,2))/2**0.5
M3 = np.reshape(U[2], (2,2))/2**0.5
M4 = np.reshape(U[3], (2,2))/2**0.5

In [63]:
M1@np.conjugate(M1).T + M2@np.conjugate(M2).T + M3@np.conjugate(M3).T + M4@np.conjugate(M4).T 

array([[1.0000000e+00+0.00000000e+00j, 6.9388939e-17+5.55111512e-17j],
       [6.9388939e-17-5.55111512e-17j, 1.0000000e+00+0.00000000e+00j]])

In [86]:
# генерирует чистое состояние
def gen_psi(d, k):
    c = np.random.randn(d*k) + 1j*np.random.randn(d*k)
    c = c/((abs(c)**2).sum()**0.5)
    return c

In [87]:
psi = gen_psi(2, 1)

In [88]:
psi_M1 = M1 @ psi /(np.conjugate(psi) @ np.conjugate(M1).T @ M1 @ psi)**0.5

In [90]:
F1_inv = inv(M1)@np.conjugate(inv(M1)).T
s, vec = np.linalg.eig(F1_inv)
c = np.sqrt(1/max(s))

In [91]:
F1_inv = inv(M1)@np.conjugate(inv(M1)).T
s, vec = np.linalg.eig(F1_inv)
c = np.sqrt(1/max(s))

M1_inv = c*inv(M1)
F2_inv = np.eye(2) - M1_inv@np.conjugate(M1_inv).T
d, u = eig(F2_inv)
M2_inv = u*d**0.5

In [100]:
s, vec = np.linalg.eig(F2_inv)
s

array([3.38441393e-16-5.13648461e-17j, 9.66887762e-01+5.13648461e-17j])

In [101]:
M1_inv@np.conjugate(M1_inv).T + M2_inv@np.conjugate(M2_inv).T

array([[ 1.00000000e+00+0.00000000e+00j, -1.11022302e-16-5.55111512e-17j],
       [-1.11022302e-16+5.55111512e-17j,  1.00000000e+00+0.00000000e+00j]])

In [102]:
psi_M1_inv = M1_inv @ psi_M1 /(np.conjugate(psi_M1) @ np.conjugate(M1_inv).T @ M1_inv @ psi_M1)**0.5

In [94]:
np.conjugate(psi)@psi_M1_inv

(1+2.7755575615628914e-16j)

In [95]:
abs(np.conjugate(psi_M1_inv)@psi_M1)**2

0.22878156473011177

In [96]:
(np.conjugate(psi_M1) @ np.conjugate(M1_inv).T @ M1_inv @ psi_M1)

(0.036320429959511985-3.469446951953614e-18j)

In [97]:
# ДЗ - максимизировать

In [98]:
def cost(a, psi):
    psi_M1 = M1 @ psi /(np.conjugate(psi) @ np.conjugate(M1).T @ M1 @ psi)**0.5
    M1_inv = a*inv(M1)
    F2_inv = np.eye(2) - M1_inv@np.conjugate(M1_inv).T
    d, u = eig(F2_inv)
    M2_inv = u*d**0.5
    
    psi_M1_inv = M1_inv @ psi_M1 /(np.conjugate(psi_M1) @ np.conjugate(M1_inv).T @ M1_inv @ psi_M1)**0.5
    return abs(np.conjugate(psi_M1_inv)@psi_M1)**2

In [99]:
cost(a = 0.3, psi = psi)

0.22878156473011194